title: "Bastion Service"
description: "Bastion Service Creation in OCI"
outputGroups:
- title: "Bastion Service"
schemaVersion: 1.1.0
locale: "en"
variableGroups:
  - title: "OCI(Oracle Cloud Infrastructure) details"
    variables:
      - compartment_ocid

  - title: "Instance configuration details"
    variables:    
      - bastion_type
      - bastion_name

  - title: "Configure Networking"
    variables: 
      - useExistingVcn
      - vcnCompartment
      - myVcn
      - subnetCompartment
      - subnet_id
      - dns_proxy_status

  - title: "Management"
    variables: 
      - max_session_ttl_in_seconds

